name: ad

services:
  ad_publisher:
    container_name: ad_publisher
    build:
      context: ./
      dockerfile: ./ad_publisher/Dockerfile
    volumes:
      - "./ad_publisher/src:/ad_publisher/src"
    ports:
      - "80:80"
    networks:
      - backend
  ad_bidder:
    container_name: ad_bidder
    build:
      context: ./
      dockerfile: ./ad_bidder/Dockerfile
    ports:
      - "81:80"
    volumes:
      - "./ad_bidder/src:/ad_bidder/src"
    env_file: ./ad_bidder/.env
    networks:
      - backend
  prom:
    container_name: prom
    build: prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
  grafana:
    container_name: grafana
    build: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend
  promtail:
    container_name: promtail
    image: "grafana/promtail:2.9.3"
    volumes:
      - ./log_shipper/promtail.yml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - backend
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100"
    networks:
      - backend
networks:
  backend:
volumes:
  grafana-storage:
#volumes:
#  ad-bidder-common:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: "./common"
