name: ad

services:
  ad_publisher:
    container_name: ad_publisher
    build:
      context: ./
      dockerfile: ./ad_publisher/Dockerfile
    volumes:
      - "./ad_publisher/src:/ad_publisher/src"
    env_file: ./ad_publisher/.env
    ports:
      - "80:80"
    networks:
      - backend
  ad_bidder:
    container_name: ad_bidder
    build:
      context: ./
      dockerfile: ./ad_bidder/Dockerfile
    ports:
      - "81:80"
    volumes:
      - "./ad_bidder/src:/ad_bidder/src"
    env_file: ./ad_bidder/.env
    networks:
      - backend
  prom:
    container_name: prom
    build: prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
  grafana:
    container_name: grafana
    build: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend
  promtail:
    container_name: promtail
    image: "grafana/promtail:2.9.5"
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - backend
  loki:
    image: grafana/loki:2.9.5
    container_name: loki
    ports:
      - "3100"
    networks:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      AD_PUBLISH_USER: ad_publish
      AD_PUBLISH_PASSWORD: ad_publish123
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
#      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - backend
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "7999:7999"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/admin?ssl=false
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      PORT: 7999
    networks:
      - backend
  mongodb-exporter:
    image: percona/mongodb_exporter:0.20
    container_name: mongodb-exporter
    environment:
        MONGODB_URI: mongodb://admin:admin@mongo:27017/admin?ssl=false
    networks:
      - backend

networks:
  backend:
volumes:
  grafana-storage:
  mongodbdata:
#volumes:
#  ad-bidder-common:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: "./common"
