services:
  ad_publisher:
    container_name: ad_publisher
    build:
      context: ./
      dockerfile: ./ad_publisher/Dockerfile
    volumes:
      - "./ad_publisher/src:/ad_publisher/src"
    ports:
      - "80:80"
    networks:
      - backend
  ad_bidder:
    container_name: ad_bidder
    build:
      context: ./
      dockerfile: ./ad_bidder/Dockerfile
    ports:
      - "81:80"
    volumes:
      - "./ad_bidder/src:/ad_bidder/src"
    env_file: ./ad_bidder/.env
    networks:
      - backend
  metric:
    container_name: metric
    build: ./metric
    ports:
      - "9090:9090"
    networks:
      - backend
  monitoring:
    container_name: monitoring
    build: ./monitoring
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend
networks:
  backend:
volumes:
  grafana-storage:
#volumes:
#  ad-bidder-common:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: "./common"
