services:
  ad_publisher:
    container_name: ad_publisher
    build:
      context: ./
      dockerfile: ./ad_publisher/Dockerfile
    volumes:
      - "./ad_publisher/app:/ad_publisher/app"
    ports:
      - "80:80"
    networks:
      - backend
  ad_bidder:
    container_name: ad_bidder
    build:
      context: ./
      dockerfile: ./ad_bidder/Dockerfile
    volumes:
      - "./ad_bidder/app:/ad_bidder/app"
    ports:
      - "81:80"
    networks:
      - backend
networks:
  backend:
#volumes:
#  ad-bidder-common:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: "./common"
