AD_PUBLISHER_API_ROOT = "/api/v1"

AD_PUBLISHER_ADS_ROOT = f"{AD_PUBLISHER_API_ROOT}/ads"

AD_BIDDER_URL_ROOT = f"http://ad_bidder:80"
AD_BIDDER_API_ROOT = "/api/v1"
AD_BIDDER_URL_BIDS_ROOT = f"{AD_BIDDER_URL_ROOT}{AD_BIDDER_API_ROOT}/bids"
AD_BIDDER_URL_BIDS_REQUEST = f"{AD_BIDDER_URL_ROOT}{AD_BIDDER_API_ROOT}/bids/request"
AD_BIDDER_URL_BIDS_BID = f"{AD_BIDDER_URL_BIDS_ROOT}{AD_BIDDER_API_ROOT}/{{bid_id}}"
AD_BIDDER_URL_BIDS_BID_NOTICE = f"{AD_BIDDER_URL_BIDS_BID}{AD_BIDDER_API_ROOT}/notice"
